apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "firefox.fullname" . }}
  labels:
    app: {{ include "firefox.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "firefox.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "firefox.name" . }}
    spec:
      containers:
        - name: firefox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "firefox.fullname" . }}-pvc
